# Site settings
title: Bitcoin Manchester
location: "Manchester, UK"
description: "Bitcoin events and information in Manchester"
baseurl: ""
url: "http://www.manchester.org.uk"

# More settings
accent: "#00BBFF" # From the logo
github: "bitcoinmanchester/bitcoinmanchester.github.io"
contact: "hello@bitcoinmanchester.org.uk"
organizers: "The Bitcoin Manchester Team"
email: "hello@bitcoinmanchester.org.uk"

# Get Meetup Notifications, visible or hidden
notifications: "visible"

# Build settings
markdown: kramdown
permalink: pretty

timezone: Europe/London

gems:
  - jekyll-redirect-from
