# Site settings
title: Bitcoin Manchester
location: "Manchester, UK"
description: "Bitcoin events and information in Manchester"
baseurl: ""
url: "http://www.bitcoinmanchester.org.uk"
permalink: /:categories/:title

# More settings
accent: "#00BBFF" # From the logo
github: "bitcoinmanchester/bitcoinmanchester.github.io"
contact: "hello@bitcoinmanchester.org.uk"
organisers: "The Bitcoin Manchester Team"
email: "hello@bitcoinmanchester.org.uk"

# Build settings
markdown: kramdown
permalink: /:categories/:title

timezone: Europe/London

gems:
  - jekyll-redirect-from

future: true

prose:
  rooturl: '_posts'
  siteurl: 'https://www.bitcoinmanchester.org.uk/'
  media: 'media'
  ignore:
    - index.html
    - meetups.html
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "select"
          options:
            - name: 'meetup'
              value: 'meetup'
            - name: 'blog'
              value: 'blog'
      - name: "author"
        field:
          element: "text"
          label: "Author (Passcard w/ leading +)"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "date"
        field:
          element: "text"
          label: "Date (YYYY-MM-DD HH:MM:SS)"
          value: "2014-06-08 10:30:00"
      - name: "host"
        field:
          element: "text"
          label: "Host"
          value: ""
      - name: "address"
        field:
          element: "text"
          label: "Address"
          value: ""
      - name: "link"
        field:
          element: "text"
          label: "Link to RSVP site (Meetup.com, etc)"
          value: ""
