# Site settings
title: Bitcoin Manchester
location: "Manchester, UK"
description: "Bitcoin events and information in Manchester"
baseurl: ""
url: "http://www.bitcoinmanchester.org.uk"
permalink: /:categories/:title

# More settings
accent: "#00BBFF" # From the logo
github: "bitcoinmanchester/bitcoinmanchester.github.io"
contact: "hello@bitcoinmanchester.org.uk"
organisers: "The Bitcoin Manchester Team"
email: "hello@bitcoinmanchester.org.uk"

# Get Meetup Notifications, visible or hidden
notifications: "visible"

# Build settings
markdown: kramdown
permalink: /:categories/:title

timezone: Europe/London

gems:
  - jekyll-redirect-from

future: true

defaults:
  - scope:
      path: ""
      # type: "meetings"
    values:
      layout: "meetup"
      foo: "bar"
